bookings/urls.py
from django.urls import path
from . import views as booking_views

app_name = 'bookings'

urlpatterns = [
    path('', booking_views.booking_home, name='booking-home'),
    path('marriage-hall', booking_views.marriage_booking, name='marriage-booking'),
]

temple_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.index, name='site-home'),
    path('history', main_views.temple_history, name="temple-history"),
    path('administration', main_views.temple_administration, name='temple-administration'),
    path('contact-us', main_views.contact_us, name='temple-contact-us'),
    path('booking/', include('bookings.urls', namespace='bookings-urls')),
]

admin/models.py
from django.db import models

# Create your models here.

bookings/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

offerings/models.py
from django.db import models

# Create your models here.

payments/models.py
from django.db import models

# Create your models here.

virtual_gallery/models.py
from django.db import models

# Create your models here.

bookings/forms.py
import re
from django import forms


class MarriageBooking(forms.Form):
    name = forms.CharField(max_length=20, required=True)
    contact_number = forms.CharField(required=True)
    marriage_date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], required=True)
    wedding_card = forms.FileField(required=True)

    name.widget.attrs.update({'class': 'form-control'})
    contact_number.widget.attrs.update({'class': 'form-control'})
    marriage_date.widget.attrs.update({'class': 'form-control'})
    wedding_card.widget.attrs.update({'class': 'form-control'})

    def clean_wedding_card(self):
        file = self.cleaned_data['wedding_card']
        file_ext = file.name.split('.')[1]
        if file_ext.lower() not in ['jpg', 'jpeg', 'bmp', 'png', 'pdf', 'doc']:
            raise forms.ValidationError('File format is not valid!')
        return file

    def clean_contact_number(self):
        user_input = self.cleaned_data['contact_number']
        pattern = r'^[+0-9\s]{10,14}$'
        if re.match(pattern, user_input):
            return user_input
        raise forms.ValidationError('Not a valid contact number!')

main/forms.py
from django import forms


class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=25, required=True)
    email = forms.EmailField(max_length=25, required=True)
    enquiry = forms.CharField(min_length=10, max_length=200, required=True, widget=forms.Textarea)

    name.widget.attrs.update({'class': 'form-control'})
    email.widget.attrs.update({'class': 'form-control'})
    enquiry.widget.attrs.update({'class': 'form-control'})

admin/views.py
from django.shortcuts import render

# Create your views here.

bookings/views.py
from django.shortcuts import render
from .forms import MarriageBooking
from utils.email import Email


def booking_home(request):
    return render(request, 'booking_home.html')


def marriage_booking(request):
    email_template = '''Hi Admin, \n\n You have received a booking for marriage hall. Details below.\n
    Name: {}\n
    Contact number: {} \n
    Marriage date: {} \n
    Wedding card is attached FYR. \n\n\n
    Thanks,\n
    Webmaster
    '''
    message = ''
    error_form = ''
    if request.method == 'POST':
        form = MarriageBooking(request.POST, request.FILES)
        if form.is_valid():
            try:
                form_data = form.cleaned_data
                email_body = email_template.format(form_data.get('name'), form_data.get('contact_number'),
                                                   form_data.get('marriage_date'))
                attachment = form_data.get('wedding_card')
                Email.send(attachment, subject='Marriage Hall Booking', message=email_body,
                           to_list=['anoopksreyas@gmail.com'])
                message = "Marriage Hall Booking submitted."
            except Exception as e:
                print(str(e))
                message = "Booking could n\'t be completed!"
        else:
            print(form.errors)
            error_form = form
    form = MarriageBooking()
    return render(request, 'marriage_booking.html', {'marriage_form': form, 'message': message,
                                                     'error_form': error_form})

events/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render

from .forms import ContactUsForm


def index(request):
    return render(request, 'index.html')


def temple_history(request):
    return render(request, 'temple_history.html')


def temple_administration(request):
    return render(request, 'temple_administration.html')


def contact_us(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            name = form_data.get('name')
            email = form_data.get('email')
            enquiry = form_data.get('enquiry')
    form = ContactUsForm()

    return render(request, 'contact_us.html', {'contact_form': form})

offerings/views.py
from django.shortcuts import render

# Create your views here.

payments/views.py
from django.shortcuts import render

# Create your views here.

virtual_gallery/views.py
from django.shortcuts import render

# Create your views here.

bookings/templates/booking_home.html
{% extends 'base.html' %}
{% block 'main-content' %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="section-container text-center border mt-5 mb-5 p-4 bg-info">
                    <a class="text-white" href="{% url 'bookings-urls:marriage-booking' %}">Marriage Hall</a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="section-container text-center border mt-5 mb-5 p-4 bg-info">
                    <a href="#" class="text-white">Vazhipadu</a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="section-container text-center border mt-5 mb-5 p-4 bg-info">
                    <a href="#" class="text-white">Choroon</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

bookings/templates/marriage_booking.html
{% extends 'base.html' %}
{% block 'main-content' %}
    <div class="container-fluid">
        {% if message %}
            <div class="row">
                <div class="col-md-6">
                    <div class="small alert alert-primary mt-3 ml-5" role="alert">{{message}}</div>
                </div>
            </div>
        {% endif %}
        {% if error_form %}
            <div class="row">
                <div class="col-md-6">
                    <div class="small alert alert-primary mt-3 ml-5" role="alert">
                        <ul class="">
                            {% for field in error_form %}
                                {% if field.errors %}
                                    <li class="">{{field.label}}: {{field.errors|striptags}}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-8">
                <form role="form" method="post" action="{% url 'bookings-urls:marriage-booking' %}" autocomplete="off"
                      class="my-5 ml-5" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for each_element in marriage_form %}
                        <div class="form-group row align-items-center">
                            <label class="col-sm-3 col-form-label">* {{ each_element.label }} :</label>
                            <div class="col-sm-5">{{ each_element }}</div>
                        </div>
                    {% endfor %}
                    <div class="form-group row">
                        <div class="col-sm-10">
                          <center><button class="submit-mock-test-btn btn btn-primary">SUBMIT</button></center>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block 'custom_scripts' %}
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <script>
    $(function () {
        $("#id_marriage_date").datetimepicker({
          format: 'd/m/Y H:i',
        });
    });
</script>
{% endblock %}

main/templates/contact_us.html
{% extends 'base.html' %}
{% block 'main-content' %}
<div class="fluid-container">
    <div class="row">
        <div class="col-md-6">
            <form role="form" method="post" action="{% url 'temple-contact-us' %}" autocomplete="off" class="my-5 ml-5">
                {% csrf_token %}
                {% for each_element in contact_form %}
                    <div class="form-group row align-items-center">
                        <label class="col-sm-2 col-form-label">* {{ each_element.label }} :</label>
                        <div class="col-sm-6">{{ each_element }}</div>
                    </div>
                {% endfor %}
<!--                <div class="form-group row">-->
<!--                    <div class="col-sm-2"></div>-->
<!--                    <div class="col-sm-6">-->
<!--                        <div class="g-recaptcha" data-sitekey="6LcMLoMUAAAAAEMe_PdCJBV-w2bPs0N4iISniGjO"></div>-->
<!--                    </div>-->
<!--                </div>-->
                <div class="form-group row">
                    <div class="col-sm-10">
                      <center><button class="submit-mock-test-btn btn btn-primary">SUBMIT</button></center>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <div class="my-5 mr-5 border">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3907.905346598779!2d76.06472821429323!3d11.630094746037132!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba6735c7aaf396b%3A0xec7dc870edf3340d!2sManiyankottappan%20Temple!5e0!3m2!1sen!2sin!4v1585659869288!5m2!1sen!2sin" width="610" height="400" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% block 'main-content' %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="section-container border mt-5 mb-5 p-4">
                    <div class="section-heading">
                        <h5>History</h5>
                        <hr/>
                    </div>
                    <div class="section-content">
                        <p class="text-justify">Sri Maniyankottappan temple is one of the encient relegious place in Kerala. Its situated in
                        Kalpetta, capital town of Wayanad district. Now its under the administration of
                            Malabar Devassom Board.</p>
                        <p class="mt-2 text-justify">Its believed that since centuries the diaty was present in the location and
                            people were worshiping it. Then on 19th century its by the effort of natives in Maniyankode,
                            they rebuilds the temple.</p>
                        <p><a href="{% url 'temple-history' %}">Read more</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="section-container border mt-5 mb-5 p-4">
                    <div class="section-heading">
                        <h5>Administration</h5>
                        <hr/>
                    </div>
                    <div class="section-content">
                        <p class="text-justify">Sri Maniyankottappan temple is one of the encient relegious place in Kerala. Its situated in
                        Kalpetta, capital town of Wayanad district. Now its under the administration of
                            Malabar Devassom Board.</p>
                        <p class="mt-2 text-justify">Its believed that since centuries the diaty was present in the location and
                            people were worshiping it. Then on 19th century its by the effort of natives in Maniyankode,
                            they rebuilds the temple.</p>
                        <p><a href="{% url 'temple-administration' %}">Read more</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="section-container border mt-5 mb-5 p-4">
                    <div class="section-heading">
                        <h5>Rituals</h5>
                        <hr/>
                    </div>
                    <div class="section-content">
                        <p class="text-justify">Sri Maniyankottappan temple is one of the encient relegious place in Kerala. Its situated in
                        Kalpetta, capital town of Wayanad district. Now its under the administration of
                            Malabar Devassom Board.</p>
                        <p class="mt-2 text-justify">Its believed that since centuries the diaty was present in the location and
                            people were worshiping it. Then on 19th century its by the effort of natives in Maniyankode,
                            they rebuilds the temple.</p>
                        <p><a href="#">Read more</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/temple_administration.html
{% extends 'base.html' %}
{% block 'main-content' %}
    {% load static %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="section-container border mt-5 mb-5 p-4">
                    <div class="section-heading">
                        <h5>Administration</h5>
                        <hr/>
                    </div>
                    <div class="section-content">
                        <p class="text-justify">
                            Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                            all the success of the temple.
                        </p>
                        <h5>Trustee Board Members</h5>
                        <div class="row">
                            <div class="col-md-12">
                                <h6 class="mt-3">Chairman</h6>
                                <div class="row">
                                    <div class="col-md-4">
                                        <span>Kamal Kumar</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-2"><img class="border mt-2" src="{% static '/images/ANOOP.jpg' %}"></div>
                            <div class="col-sm-10">
                                <span class="text-justify">
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                </span>
                            </div>
                        </div>
                        <hr/>
                        <div class="row">
                            <div class="col-md-12">
                                <h6 class="mt-3">President</h6>
                                <div class="row">
                                    <div class="col-md-4">
                                        <span>Kamal Kumar</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-2"><img class="border" src="{% static '/images/ANOOP.jpg' %}"></div>
                            <div class="col-sm-10">
                                <span class="text-justify">
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                </span>
                            </div>
                        </div>
                        <hr/>
                        <div class="row">
                            <div class="col-md-12">
                                <h6 class="mt-3">Secretary</h6>
                                <div class="row">
                                    <div class="col-md-4">
                                        <span>Kamal Kumar</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-2"><img class="border" src="{% static '/images/ANOOP.jpg' %}"></div>
                            <div class="col-sm-10">
                                <span class="text-justify">
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                    Temple is administered by a team of talented people. Their hardwork and teamwork is behind
                                    all the success of the temple.
                                </span>
                            </div>
                        </div>
                        <hr/>
                        <p><a href="{% url 'site-home' %}">Home</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/temple_history.html
{% extends 'base.html' %}
{% block 'main-content' %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="section-container border mt-5 mb-5 p-4">
                    <div class="section-heading">
                        <h5>History</h5>
                        <hr/>
                    </div>
                    <div class="section-content">
                        <p class="text-justify">Sri Maniyankottappan temple is one of the encient relegious place in Kerala. Its situated in
                        Kalpetta, capital town of Wayanad district. Now its under the administration of
                            Malabar Devassom Board.</p>
                        <p class="mt-2 text-justify">Its believed that since centuries the diaty was present in the location and
                            people were worshiping it. Then on 19th century its by the effort of natives in Maniyankode,
                            they rebuilds the temple.</p>
                        <p><a href="{% url 'site-home' %}">Home</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv = "X-UA-Compatible" content = "IE = edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block 'title' %}
        <title>:: Maniyankottappan Temple ::</title>
    {% endblock %}
    {% block 'header-scripts' %}
        <link rel="stylesheet" href="{% static '/styles/bootstrap.min.css' %}" >
        <link rel="stylesheet" href="{% static '/styles/custom.css' %}" >
    {% endblock %}
</head>
<body>
    {% block 'header' %}
        {% include 'header.html' %}
    {% endblock %}

    {% block 'main-content' %}

    {% endblock %}

    {% block 'footer' %}
        {% include 'footer.html' %}
    {% endblock %}

    {% block 'footer-scripts' %}
        <script src="{% static '/scripts/jquery-3.3.1.min.js' %}" rel="script"></script>
        <script src="{% static '/scripts/propper.min.js' %}" rel="script"></script>
        <script src="{% static '/scripts/bootstrap.min.js' %}" rel="script"></script>
    {% endblock %}

    {% block 'custom_scripts' %}

    {% endblock %}
</body>
</html>

templates/footer.html
<!-- Footer -->
	<section id="footer">
		<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left">
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Quick links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="{% url 'site-home' %}"><i class="fa fa-angle-double-right"></i>Home</a></li>
						<li><a href="{% url 'temple-history' %}"><i class="fa fa-angle-double-right"></i>History</a></li>
						<li><a href="{% url 'temple-administration' %}"><i class="fa fa-angle-double-right"></i>Administration</a></li>
						<li><a href="{% url 'temple-contact-us' %}"><i class="fa fa-angle-double-right"></i>Contact Us</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Quick links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="{% url 'bookings-urls:booking-home' %}"><i class="fa fa-angle-double-right"></i>Booking</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Events</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Archives</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Gallery</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Quick links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Donate</a></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
					</ul>
				</div>
				</hr>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="#" target="_blank">Sree Maniyankottappan Temple</a></p>
				</div>
				</hr>
			</div>
		</div>
	</section>
	<!-- ./Footer -->

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'site-home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'temple-history' %}">History</a>
      </li>
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Booking-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Marriage Hall</a>-->
<!--          <a class="dropdown-item" href="#">Choroon</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#"Thulabharam</a>-->
<!--        </div>-->
<!--      </li>-->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'temple-administration' %}">Administration</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bookings-urls:booking-home' %}">Booking</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Offerings</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'temple-contact-us' %}">Contact Us</a>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>
<!--    <form class="form-inline my-2 my-lg-0">-->
<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
  </div>
</nav>